blank_issue_enabled: false
contact_links:
- name: Questions / Support
  about: GitHub issues are not the right place to ask question, please join our discord community for questions / support.
  url: https://discord.gg/FQ5vgW3
