name: 🚀 Feature Request
description: I have a suggestion!
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
          required: true
        - label: This issue specifically has something to do with Twitch4J
          required: true
        - label: I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the feature/enhancement.
      placeholder: e.g. I have an issue when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Teachability, Documentation, Adoption, Migration Strategy