blank_issue_enabled: false
contact_links:
  - name: Ask the question
    about: Issue tracker is not for question. Please go to the Discord channel asking question.
    url: https://discord.gg/FQ5vgW3